apiVersion: v1
kind: ServiceAccount
metadata:
  name: consul-sidecar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: consul-sidecar
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["serviceaccounts", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-sidecar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-sidecar
subjects:
  - kind: ServiceAccount
    name: consul-sidecar
    namespace: default
